from enum import Enum

class VideoStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class CustomerStatus(str, Enum):
    ACTIVE = "ACTIVE"
    EXITED = "EXITED"

class BasketStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ABANDONED = "ABANDONED"
    EXITED = "EXITED"

class EntityType(str, Enum):
    CUSTOMER = "CUSTOMER"
    BASKET = "BASKET"
    VIDEO = "VIDEO"
    SYSTEM = "SYSTEM"

class EventType(str, Enum):
    CUSTOMER_ENTERED = "CUSTOMER_ENTERED"
    CUSTOMER_ACTIVE = "CUSTOMER_ACTIVE"
    CUSTOMER_EXITED = "CUSTOMER_EXITED"
    BASKET_DETECTED = "BASKET_DETECTED"
    BASKET_ACTIVE = "BASKET_ACTIVE"
    ZONE_ENTERED = "ZONE_ENTERED"
    ZONE_EXITED = "ZONE_EXITED"
    SHELF_INTERACTION = "SHELF_INTERACTION"
    LONG_DWELL_TIME = "LONG_DWELL_TIME"
    UNUSUAL_ZONE_TRANSITION = "UNUSUAL_ZONE_TRANSITION"
    PRODUCT_PICKED = "PRODUCT_PICKED"
    PRODUCT_IN_BASKET = "PRODUCT_IN_BASKET"
    PRODUCT_RETURNED = "PRODUCT_RETURNED"
    PRODUCT_UNRESOLVED = "PRODUCT_UNRESOLVED"
    SUSPICIOUS_BEHAVIOR = "SUSPICIOUS_BEHAVIOR"
    POSSIBLE_CONCEALMENT = "POSSIBLE_CONCEALMENT"
    HIGH_RISK_DETECTED = "HIGH_RISK_DETECTED"

class RiskLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class AlertSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class AlertStatus(str, Enum):
    ACTIVE = "ACTIVE"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"

class IncidentStatus(str, Enum):
    OPEN = "OPEN"
    UNDER_REVIEW = "UNDER_REVIEW"
    CLOSED = "CLOSED"
